### ISSUE TITLE
Find appropriate clustering/community detection algorithm

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NW-Extension#77]
To replace k-means. See #38.

**Comment by cogijl** [comment]
Not sure if any work has been done on this, but it would seem that Louvain may be the way to go because of its efficiency compared to other ways of doing it. 
I found some work on doing this for gephi https://github.com/socialsensor/social-event-detection/blob/master/src/clustering/louvain/LouvainClustering.java 
It seems that this may be the best way to do it but I don't know if it is already in the works. I'll be moving to a position in the fall that may allow me to work on this if not.

**Comment by qiemem** [comment]
I've been thinking about this again recently with the coming release of NetLogo 6.0

I think the Louvain method is the way to go: it's crazy fast, and significantly more accurate than other "fast" methods: https://en.wikipedia.org/wiki/Louvain_Modularity#Comparison_to_Other_Methods

One (I guess?) downside is that it's both hierarchical and doesn't do binary splits. Generally, this is actually a good thing, but it means that we can't simply take in a desired number of clusters.

One idea I had was to make the iterative nature of the method explicit. First, a quick explanation of the Louvain method. It takes place in two phases:

First phase:

1. Assign each node to it's own community.
2. Iterate over each node, calculating the change in modularity that would occur if it were removed from it's current community and put in a connected community. Move it to the community that produces the biggest increase in modularity.
3. Repeat step 2 until we can't increase modularity anymore.

Second phase:

1. Create a new network, formed by the communities that were produced in the first phase, with weights of links calculated from the sum of the weights of links between the communities, and internal links becoming a single self-loop.
2. Perform the first phase on this new network. That is, we're calculating communities of communities.

We then repeat these two phases until we've only got one community.

So here's my idea: we add `nw:louvain-communities <list-of-agentset-communities>` that takes in a (optional) list of communities. It then performs the first phase using those communities as nodes and returns the resulting list of merged communities. If no list is provided, it uses a default argument of `[ turtle-set self ] of turtles`: that is, a list of communities, each only containing a single turtle (which is how the Louvain method is normally initialized).

The user may then iteratively apply the method however they want. So, if they want to get less than  some number of communities, they can do:

```
let communities nw:louvain-communities
while [ length communities > 10 ] [
  set communities (nw:louvain-communities communities)
]
```

Alternatively, they could stop when a certain modularity is reached or whatever.

What I like about this:

- It's super flexible
- Full hierarchical information is preserved if desired
- Relatively simple interface
- Don't have to explicitly specify number of communities if you don't want to

What do you guys think?

**Comment by qiemem** [comment]
Quick follow-up: the Louvain method implicitly works for weighted networks as well. Would that be useful to expose? It does complicate the API somewhat.

**Comment by arthurhjorth** [comment]
I really like your suggestion, @qiemem and I would be happy to see that implemented. 

But, will we have no way of finding 'n' clusters, then? That really feels like something we should have, doesn't it?

**Comment by arthurhjorth** [comment]
And yes please to weighted networks. Definitely useful!

**Comment by qiemem** [comment]
> But, will we have no way of finding 'n' clusters, then? That really feels like something we should have, doesn't it?

I'm not sure. That's what we've been beaten into thinking we need, but I think that's mostly because, historically, it's been easier to find `n` clusters than find a natural number of clusters at a given resolution. That is, nobody likes the `k` in `k`-means.

**Comment by arthurhjorth** [comment]
But isn't that mostly because k-means assumes equal sizes (or rather, the centroids optimize against that), and often they aren't so it's just that useful? Aren't there more clever algos that still allow you to specify a number?  I don't know anywhere near as much as you do about this, and maybe I just haven't thought it through. But it does seem like a nice way to quickly look at your data for stuff.

**Comment by qiemem** [comment]
Giving a `k` imposes a lot of assumptions on the data (namely, that you have `k` communities!)

> Aren't there more clever algos that still allow you to specify a number?

Um, sort of. Other modularity maximization techniques that I know of kind of suck. You specify a max number of communities, but they don't have to use them.

Girvan-Newman does binary splits, which effectively allows you to choose the number (though it's better to treat the result as hierarchical), but it's crazy slow. Actually, a number of algorithms do binary splits or merges.

**Comment by wvermeer** [comment]
I feel louvain is certainly the way to go, in terms of quick methods go, it is very much the golden standard. I also agree with the ittarative approach which greatly increases the flexibility of the procedure. While I see the flexiblity of providing a community structure for the procedure, i wonder if that does not make the procedure much less intuative to use... there is the question about the target audience ... which users are using this procedure, and what do they use it for, in many ways that is also what @arthurhjorth is emphasizing. flexibility does come at the cost of readability. I'd rather have a procedure which similar to other nw procedures takes all active agents/links in the context (or a subset of links and turtles).

A novice user might be interested in simpler questions like "who is part of what cluster?"... and it should be simple to get these out (rather than it being a more complicated version of the default). My intuition is we might need to include a simple version of the procedure for this. If we would take the baseline `nw:louvain-communities <number-clusters>.` which adds this while loop as proposed before to get to this result, we can have <number-clusters> default to 0 which would stop the procedure when the modularity criteria is met.

A more advanced use would be optimizing the number of communities by looking at the change in modularity. In this case a `nw:louvain-modularity <modularity-value>` procedure would output a list of changes in modularity per merge and the number of clusters at that point. The <modularity-value> would be the stopping condition, with a default of 0 (which would make it default to the full list).

An additional functionality which should be incorporated is to assign community attributes to turtles in the slected context (or turtle/linkset), a `get-community-louvain <context> <number-communities>`

**Comment by qiemem** [comment]
Thanks for the comments, @wvermeer. 

We already talked about this in person, but I think you're right about my proposal being a little too complicated.

As you pointed, also, there is a natural stopping point for the Louvain algorithm: when modularity is maximized of course!

So, we could just have `nw:louvain-communities` just run the complete algorithm and return the result (as a list of agentsets).

Regarding `nw:louvain-communities <number-clusters>`, the number of communities drops rapidly when running louvain. This would be so innaccurate as to be fairly useless.

We could also provide an optional argument that corresponds with my original suggestion so that you could do that other stuff for advanced users.

Next, regarding your suggestion of assigning an attribute to turtles, under the current proposal, this would look like (assuming there's a turtles-own variable `community`):

```
foreach nw:louvain-communities [ [c] ->
  ask c [ set community c ]
]
```

Now, one thing I think *would* be cool would be to have a turtle reporter `nw:louvain-community` that returns the louvain community of that turtle. The problem with this is that the louvain method is nondeterministic. We want running it multiple times to be able to return different results. Thus, we can't add that turtle procedure and maintain consistency.

**Comment by cogijl** [comment]
I think this is a great idea. I do a lot of work in data analysis for the
social sciences that is used to validate agent based models and this
feature could potentially be a great addition that creates a link between
the social network analysis / community detection a lot of researchers are
doing and the agent based models.
Overall I prefer Louvain to other community detection.
It will also put NetLogo further ahead of non-open source competition which
is generally lacking in this regard.

**Comment by qiemem** [comment]
Thanks for the feedback, @cogijl! Definitely planning on going with Louvain. Hopefully have it done this weekend.

**Comment by qiemem** [comment]
Alright, I've implemented it! A few points:

- It's entirely deterministic at the moment. There are a number of advantages (and disadvantages) of this, but one thing is that we could give turtles an `nw:louvain-community` reporter that returns the community that that turtle is a part of. This saves users some trouble, but I'm not sure how much. Thoughts?
- The advantage of being random is that if you get a bad community division you can rerun it to try to get a better one. That said, Louvain is typically pretty consistent, so I don't think it matters that much. Objections?
- No weighted version yet. I don't think I'll have time to do one for the moment, though adding it will be pretty easy (as the algorithm already uses weights).

**Comment by qiemem** [comment]
I'm closing this for now. If anyone would like to see changes to this, feel free to re-open.

**Comment by BrandonKMLee** [comment]
Questions from the future: GN and infomap being the top two "hierarchical" algorithms, since CDLib, the top community detection library, is not ready for granularity.

**Comment by cogijl** [comment]
> 

Not sure how I missed this, but wanted to give thanks for the work you put in all those years ago! There's a beer with your name on it if you're ever in Bratislava!
